### ISSUE TITLE
Expose API diff

### ISSUE THREAD

**Issue by markemeis** [CATechnologiesTest/yipee#23]
Expose an endpoint which takes two arguments.  The types of arguments can be Namespace name, Yml file, flat file (UI format)

**Comment by jd3quist** [comment]
POST to /diff.  Payload definition:

```
{
  parent: <diffobj>,
  children: <array-of-diff-obj>
}
```

A _diff-obj_ looks like this:

```
{
  name: <string>,
  (optional) data: <yaml-string | GUID | flat-object>
}
```

If _data_ is not present, name is assumed to be a namespace (for diff of deployed namespaces in "live" mode)
