### ISSUE TITLE
Ability to import Helm chart

### ISSUE THREAD

**Issue by markemeis** [CATechnologiesTest/yipee#33]
Similar to importing Docker compose and Kubernetes YAML, provide an import for Helm Charts.

I'd expect the values file to be combined with the template in Yipee.io.  With the Diff capability, I'd expected to be able to import twice with two different values files and see the differences.

**Comment by jrryjcksn** [comment]
We new support importing Helm charts via the normal import path (using the default Values.yaml file from the chart). Adding the ability to select external values files is postponed.
