### ISSUE TITLE
Host error on ingress rule not displaying

### ISSUE THREAD

**Issue by andrewcopley** [CATechnologiesTest/yipee#39]
The Host field in an ingress rule is not displaying any errors. It displays the error image next to the rule, but also needs to display the error text so the user knows what is wrong.

**Comment by andrewcopley** [comment]
Investigated and found host has no tooltip error display. Can be fixed by adding the display error like other error tooltips.

**Comment by andrewcopley** [comment]
Fixed on yipee public repo. PR is up.

**Comment by markemeis** [comment]
@andrewcopley is this complete and merged into yipee?  If so, can you move to done?
