### ISSUE TITLE
Unknown kind not showing the properties page

### ISSUE THREAD

**Issue by markemeis** [CATechnologiesTest/yipee#5]
Steps to reproduce
1. add service|container group to your applications
1. add an unknown kind object to your model
1. click on the blank part of the canvas
1. click on the unknown kind object

Expected results - see the properties for the unknown kind
Actual results - app stays on the application properties.

Workaround - select either your service or container group then your unknown kind

**Comment by markemeis** [comment]
@bl8nr can you take a look at this?

**Comment by andrewcopley** [comment]
The problem is that if you click from a canvas object to the canvas info pane, you cannot click back to the object you clicked before clicking the canvas. But you can click other objects.
