### ISSUE TITLE
Remove all references to 'korn' (the internal code name) in the UI

### ISSUE THREAD

**Issue by markemeis** [CATechnologiesTest/yipee#6]
There are places in the code that reference 'korn' the internal code name for the UI.  Need to replace them.

**Comment by markemeis** [comment]
@jd3quist is "source=korn" required on the api calls?  That appears to be the remaining references.

**Comment by markemeis** [comment]
The majority of the korn references was addressed via https://github.com/yipeeio/yipee/pull/13

**Comment by jd3quist** [comment]
@markemeis The api does not require (or pay attention to) query string parameters on any calls.  So, no, "source=korn" is not required on any api call.

**Comment by andrewcopley** [comment]
@jd3quist I removed all korn references in the ui code. There are 3 files in the backend that reference korn. Might want to take a look at those and see if you think they can be removed. I'm just not sure. You can make those changes on the branch remove-korn-references-#6 that I made if you like. Theres a PR up for it on yipeeio-yipee.

**Comment by jd3quist** [comment]
@andrewcopley I'm not clear on those backend references.  Since you've determined that there are 3 backend files can you tell me what they are?

**Comment by andrewcopley** [comment]
Talked with jim, and it was determined the 3 references do not need to be removed. This card should be finished. PR is up on yipeeio-yipee.

**Comment by jd3quist** [comment]
These are the 3 refs AJ mentioned:
- a comment referring to korn-dashboard image in source code [it's an XXX suggesting future direction when we have a "live" image other than korn-dashboard]
- an image name in a testdata file used in converter unit tests [doesn't matter at all -- image name could be anything and there's no public visibility]
- image: spec in the experimental/live.yaml file.  [this should change if/when we have a "live" image other than korn-dashboard]

Not planning to change any of those right now.
