### ISSUE TITLE
Service selectors and generated labels have "yipee.io" instead of "yipee" in the name

### ISSUE THREAD

**Issue by markemeis** [CATechnologiesTest/yipee#8]
When connecting a service to a container group, it adds labels to the container group named "yipee.io/<service name>".  The name of the label should be "yipee/<service name>"

**Comment by jlegrone** [comment]
Hey just stopping by, this looks like a cool project! Please let me know if I'm misunderstanding this issue, but the Kubernetes docs recommend valid subdomains as label prefixes. It would be ideal if this tool followed that convention.

Reference: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

> If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/).

**Comment by jd3quist** [comment]
Thanks jlegrone (and sorry for the slow response).  You're absolutely right about the label prefixes.  We'll leave them as "yipee.io".
